name: Annotation
on: push
jobs:
  first: 
    runs-on: ubuntu-latest
    steps:
      - run: sleep 10 && echo "first"
  second: 
    runs-on: ubuntu-latest
    steps:
      - run: sleep 10 && echo "second"
  third: 
    runs-on: ubuntu-latest
    steps:
      - run: sleep 10 && echo "third"
      
      