name: Hello
on: push
jobs:
  hello: 
    runs-on: ubuntu-latest
    env: 
      USERNAME: ${{vars.USERNAME}}
      TEST: ${{ vars.TEST }}
      SECRET: ${{secrets.SECRET }}
    steps:
      - run: echo "${USERNAME}"
      - run: echo "${TEST}"
      - run: echo "${SECRET}"

      